name: Build Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip monster-highlighter-1.21.11-Fabric.zip

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          cd monster-highlighter-1.21.11-Fabric
          chmod +x gradlew
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: monster-highlighter-1.21.11-Fabric/build/libs/*.jar
